-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE babel (
  babel_user INT NOT NULL,
  babel_lang TEXT NOT NULL,
  babel_level TEXT NOT NULL,
  PRIMARY KEY(babel_user, babel_lang)
);

CREATE INDEX babel_lang_level ON babel (babel_lang, babel_level);
