-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/babel (
  babel_user INT UNSIGNED NOT NULL,
  babel_lang VARBINARY(35) NOT NULL,
  babel_level VARBINARY(2) NOT NULL,
  INDEX babel_lang_level (babel_lang, babel_level),
  PRIMARY KEY(babel_user, babel_lang)
) /*$wgDBTableOptions*/;
