-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/babel (
  babel_user INTEGER UNSIGNED NOT NULL,
  babel_lang BLOB NOT NULL,
  babel_level BLOB NOT NULL,
  PRIMARY KEY(babel_user, babel_lang)
);

CREATE INDEX babel_lang_level ON /*_*/babel (babel_lang, babel_level);
